config/routes.rb
LetsWrite::Application.routes.draw do
  get "pages/about"

  get "pages/programs"

  get "pages/contact"

  get "pages/gallery"

  root :to => 'pages#programs'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def programs
  end

  def contact
  end

  def gallery
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	
	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
	
	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Tangerine Web Font -->
  <link href='http://fonts.googleapis.com/css?family=Tangerine:700' rel='stylesheet' type='text/css'>

	<title>LetsWrite</title>
  
	<!-- Included CSS Files -->
	<%= stylesheet_link_tag    "application" %>
	
	<!-- Included JS Files  -->
	<%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
</head>
<body>

    <nav class="top-bar">
      <ul>
        <li class="name"><h1><a href="#">LetsWrite.com</a></h1></li>
        <li class="toggle-topbar"><a href="#"></a></li>
        <li class="divider"></li>
      </ul>
      <section>
        <ul class="right">
          <li class="divider"></li>
          <li><a href="http://letswritegw.wordpress.com">Check Out Our Blog</a></li>
          <li class="divider"></li>
        </ul>
      </section>
    </nav>

<div class="container">
  
  <div class="row">
    <div class="twelve columns" style="font-family: 'Tangerine', cursive; font-size: 8em; text-align: center;">
      Lets Write
    </div>
  </div>

  <div class="row" style="margin-top: 30px">
    <div class="three columns">
      <ul class="nav-bar vertical">
        <li><%= link_to "About Us", pages_about_path %></li>
        <li><%= link_to "Programs", pages_programs_path %></li>
        <li><%= link_to "Gallery", pages_gallery_path %></li>
        <li><%= link_to "Contact Us", pages_contact_path %></li>
      </ul>
    </div>

    <div class="nine columns">
      <%= yield %>
    </div>

  </div>

  <div class="row" style="margin-top: 30px">
    <hr />
  </div>

</div>

</body>
</html>

app/views/pages/about.html.erb
<div class="panel">

  <div class="row" style="line-height: 1.2em; text-indent: 50px;">
    <div class="twelve columns">  
      <p>
        English is a skill that cannot be developed easily in a person. Creative writing, grammar and vocabulary can’t be learnt in a day. But, our special courses show everyone, from kindergarten to high school, the path that one must take to start learning these skills while also giving them an opportunity to practice them.
      </p>
      <p>
        The three courses that we currently offer are: creative writing, story writing and storytelling. We help students open their minds and think outside the box. Exercises include expanding sentences, improving grammar and speaking English, among others. The little ones even get a change to improve pronunciation and vocabulary in a stimulating environment. Children will also be introduced to the world of story writing with its different genres.
      </p>
    </div>
  </div>

  <div class="row" style="line-height: 1.2em">
    <div class="two columns">  
      <%= image_tag("skype.png") %>
    </div>
    <div class="ten columns">  
        For students who live far away from Noida we also provide the same classes on Skype!
    </div>
  </div>

</div>

app/views/pages/contact.html.erb
<div class="row">
  <div class="six columns" style="line-height: 1.3em">

    <div class="row">
      <div class="twelve columns">
        <h3 style="text-align: center;">Ritu Vaish</h3>
      </div>
    </div>

    <div class="row">
      <div class="twelve columns">

        <div class="panel" style="line-height: 1.3em">

          <div class="row">
            <div class="three columns text-align-right">
              <strong>Email: </strong>
            </div>
            <div class="nine columns">
              <a href="mailto:rituvaish@gmail.com">rituvaish@gmail.com</a>
            </div>
          </div>

          <hr style="margin:15px" />

          <div class="row">
            <div class="three columns text-align-right">
              <strong>Phone: </strong>
            </div>
            <div class="nine columns">
              +91 9873906063
            </div>
          </div>

          <hr style="margin:15px" />

          <div class="row">
            <div class="three columns text-align-right">
              <strong>Address: </strong>
            </div>
            <div class="nine columns">
              B-126/7 Sector-41<br>B Block Market<br>Noida, 201303 (U.P.)
            </div>
          </div>

          <hr style="margin:15px" />

          <div class="row">
            <div class="three columns text-align-right">
              <strong>Blog: </strong>
            </div>
            <div class="nine columns">
              <a href="http://letswritegw.wordpress.com">letswritegw.wordpress.com</a>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>

  <div class="six columns" style="line-height: 1.3em">

    <div class="row">
      <div class="twelve columns">
        <h3 style="text-align: center;">Riju H Rai</h3>
      </div>
    </div>

    <div class="row">
      <div class="twelve columns">

        <div class="panel" style="line-height: 1.3em">

          <div class="row">
            <div class="three columns text-align-right">
              <strong>Email: </strong>
            </div>
            <div class="nine columns">
              <a href="mailto:riju2006@gmail.com">riju2006@gmail.com</a>
            </div>
          </div>

          <hr style="margin:15px" />

          <div class="row">
            <div class="three columns text-align-right">
              <strong>Phone: </strong>
            </div>
            <div class="nine columns">
              +91 9886320707
            </div>
          </div>

          <hr style="margin:15px" />

          <div class="row">
            <div class="three columns text-align-right">
              <strong>Address: </strong>
            </div>
            <div class="nine columns">
              C003 Colorado Apartments<br>Hennur Cross Road<br>Bangalore 560043
            </div>
          </div>

      </div>
    </div>

app/views/pages/gallery.html.erb
<script type="text/javascript">
  $(window).load(function() { 
    $("#featured").orbit();
  });
</script>

<div class="row">
  <div class="ten columns centered">
    <div id="featured">
      <%= image_tag("gallery/img01.jpg") %>   
      <%= image_tag("gallery/img03.jpg") %> 
      <%= image_tag("gallery/img04.jpg") %>
      <%= image_tag("gallery/img06.jpg") %>
      <%= image_tag("gallery/img08.jpg") %>
      <%= image_tag("gallery/img10.jpg") %>
    </div>
  </div>
</div>

app/views/pages/programs-2.html.erb
<div class="panel" style="line-height: 1.3em">

  <div class="row">
    <div class="four columns">
      <%= image_tag("creative_writing.jpg") %>
    </div>
    <div class="eight columns">
      <h4>Creative Writing</h4>
      Not everyone is a J.K.Rowling. But in this program at GW, we help students open their minds and think outside the box. Exercises include expanding sentences, improving grammar and speaking English. Previous classes included teaching the children to use their sense organs to do descriptive writing.
    </div>
  </div>

  <div class="row margin-top-medium" style="margin-top: 20px">
    <div class="four columns">
      <%= image_tag("story_telling.jpg") %>
    </div>
    <div class="eight columns">
      <h4>Story Telling</h4>
      For the kids of nursery and kindergarten we have this program that helps them with English comprehension and improving their spoken English at the same time. Bundled with lots of craft activities, the students learn 3 letter words in a stimulating environment.
    </div>
  </div>

   <div class="row margin-top-medium" style="margin-top: 20px">
    <div class="four columns">
      <%= image_tag("story_writing.jpg") %>
    </div>
    <div class="eight columns">
      <h4>Story Writing</h4>
      Children will be introduced to the world of story writing with its different genres. How to develop a story from a basic thread is a hard thing to learn, but we communicate many techniques to the students. This is a new program and innovative ideas will be introduced as the program goes along.
    </div>
  </div>

</div>

app/views/pages/programs.html.erb
<div class="row panel">

  <div class="four columns">
    <h4 class="text-align-center">Creative Writing</h4>
    <div class="row">
      <div class="twelve columns">
        <%= image_tag("creative_writing.jpg") %>
      </div>
    </div>
    <div class="row">
      <div class="twelve columns margin-top-medium" style="line-height: 1.3em">
        Not everyone is a J.K.Rowling. But in this program at GW, we help students open their minds and think outside the box. Exercises include expanding sentences, improving grammar and speaking English. Previous classes included teaching the children to use their sense organs to do descriptive writing.
      </div>
    </div>
  </div>

  <div class="four columns">
    <h4 class="text-align-center">Story Telling</h4>
    <div class="row">
      <div class="twelve columns">
        <%= image_tag("story_telling.jpg") %>
      </div>
    </div>
    <div class="row">
      <div class="twelve columns margin-top-medium" style="line-height: 1.3em">
        For the kids of nursery and kindergarten we have this program that helps them with English comprehension and improving their spoken English at the same time. Bundled with lots of craft activities, the students learn 3 letter words in a stimulating environment.
      </div>
    </div>
  </div>

  <div class="four columns">
    <h4 class="text-align-center">Story Writing</h4>
    <div class="row">
      <div class="twelve columns">
        <%= image_tag("story_writing.jpg") %>
      </div>
    </div>
    <div class="row">
      <div class="twelve columns margin-top-medium" style="line-height: 1.3em">
        Children will be introduced to the world of story writing with its different genres. How to develop a story from a basic thread is a hard thing to learn, but we communicate many techniques to the students. This is a new program and innovative ideas will be introduced as the program goes along.
      </div>
    </div>
  </div>

</div>